// <auto-generated />
using System;
using EcoTaxiAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTaxiAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531105611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EcoTaxiAPI.Models.Anketa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("acquaintances")
                        .HasColumnType("longtext");

                    b.Property<bool>("additional_info_consent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("birth_date_place")
                        .HasColumnType("longtext");

                    b.Property<string>("children_birthday")
                        .HasColumnType("longtext");

                    b.Property<string>("children_info")
                        .HasColumnType("longtext");

                    b.Property<string>("computer_skills")
                        .HasColumnType("longtext");

                    b.Property<string>("criminal_record")
                        .HasColumnType("longtext");

                    b.Property<string>("driver_years_1")
                        .HasColumnType("longtext");

                    b.Property<string>("driver_years_2")
                        .HasColumnType("longtext");

                    b.Property<string>("driver_years_3")
                        .HasColumnType("longtext");

                    b.Property<string>("driver_years_4")
                        .HasColumnType("longtext");

                    b.Property<bool>("education_higher")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("education_higher_incomplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("education_secondary_technical")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("father_birthday")
                        .HasColumnType("longtext");

                    b.Property<string>("father_phone_number")
                        .HasColumnType("longtext");

                    b.Property<string>("father_place_of_work_position")
                        .HasColumnType("longtext");

                    b.Property<string>("full_name")
                        .HasColumnType("longtext");

                    b.Property<string>("home_phone")
                        .HasColumnType("longtext");

                    b.Property<string>("language_1")
                        .HasColumnType("longtext");

                    b.Property<string>("language_2")
                        .HasColumnType("longtext");

                    b.Property<string>("language_3")
                        .HasColumnType("longtext");

                    b.Property<string>("language_level_1")
                        .HasColumnType("longtext");

                    b.Property<string>("language_level_2")
                        .HasColumnType("longtext");

                    b.Property<string>("language_level_3")
                        .HasColumnType("longtext");

                    b.Property<string>("last_workplace")
                        .HasColumnType("longtext");

                    b.Property<string>("marital_status")
                        .HasColumnType("longtext");

                    b.Property<string>("military_ticket")
                        .HasColumnType("longtext");

                    b.Property<string>("mobile_phone")
                        .HasColumnType("longtext");

                    b.Property<string>("mother_birthday")
                        .HasColumnType("longtext");

                    b.Property<string>("mother_phone_number")
                        .HasColumnType("longtext");

                    b.Property<string>("mother_place_of_work_position")
                        .HasColumnType("longtext");

                    b.Property<string>("passport_issued_by")
                        .HasColumnType("longtext");

                    b.Property<string>("passport_issued_date")
                        .HasColumnType("longtext");

                    b.Property<int>("passport_serial_number")
                        .HasColumnType("int");

                    b.Property<string>("position")
                        .HasColumnType("longtext");

                    b.Property<string>("position_1")
                        .HasColumnType("longtext");

                    b.Property<string>("position_2")
                        .HasColumnType("longtext");

                    b.Property<string>("position_3")
                        .HasColumnType("longtext");

                    b.Property<string>("position_4")
                        .HasColumnType("longtext");

                    b.Property<bool>("probation_agreement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("reason_for_leaving")
                        .HasColumnType("longtext");

                    b.Property<string>("referee")
                        .HasColumnType("longtext");

                    b.Property<string>("referee_phone")
                        .HasColumnType("longtext");

                    b.Property<string>("registration_address")
                        .HasColumnType("longtext");

                    b.Property<string>("residential_address")
                        .HasColumnType("longtext");

                    b.Property<bool>("source_job_center")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("source_newspaper")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("source_radio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("source_tv")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("source_website")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("specialty")
                        .HasColumnType("longtext");

                    b.Property<string>("spouce_birthday")
                        .HasColumnType("longtext");

                    b.Property<string>("spouce_phone_number")
                        .HasColumnType("longtext");

                    b.Property<string>("spouce_place_of_work_position")
                        .HasColumnType("longtext");

                    b.Property<string>("study_years")
                        .HasColumnType("longtext");

                    b.Property<string>("university")
                        .HasColumnType("longtext");

                    b.Property<string>("work_experience")
                        .HasColumnType("longtext");

                    b.Property<string>("work_start_date")
                        .HasColumnType("longtext");

                    b.Property<string>("workplace_1")
                        .HasColumnType("longtext");

                    b.Property<string>("workplace_2")
                        .HasColumnType("longtext");

                    b.Property<string>("workplace_3")
                        .HasColumnType("longtext");

                    b.Property<string>("workplace_4")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Anketas");
                });
#pragma warning restore 612, 618
        }
    }
}
